# Generated by Django 3.2.16 on 2022-11-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinevendas',
            name='Entrega',
            field=models.CharField(choices=[('Realizada', 'Realizada'), ('Pendente', 'Pendente')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pipelinevendas',
            name='Fase',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Negociação', 'Negociação'), ('Perdido', 'Perdido')], max_length=10),
        ),
    ]
