# Generated by Django 3.2.16 on 2022-11-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20221123_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinevendas',
            name='Data_Faturamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pipelinevendas',
            name='Fase',
            field=models.CharField(choices=[('Inicio', 'Inicio'), ('Negociação', 'Negociação'), ('Compras', 'Compras'), ('Aprovado', 'Aprovado'), ('Suspensa', 'Suspensa'), ('Reprovado preço', 'Reprovado preço')], max_length=20),
        ),
    ]
