# Generated by Django 3.2.16 on 2022-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_auto_20221125_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinevendas',
            name='idProposta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
