# Generated by Django 2.1.15 on 2022-11-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faturamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_dia', models.CharField(max_length=255)),
                ('data_faturamento', models.DateTimeField()),
                ('data_update', models.DateField(auto_now=True)),
            ],
        ),
    ]
