# Generated by Django 2.1.15 on 2022-11-04 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_concluido_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concluido',
            old_name='descricao',
            new_name='descricao_concluido',
        ),
        migrations.RenameField(
            model_name='curso',
            old_name='descricao',
            new_name='descricao_curso',
        ),
        migrations.RenameField(
            model_name='planejado',
            old_name='descricao',
            new_name='descricao_planejado',
        ),
    ]
