# Generated by Django 2.1.15 on 2022-11-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20221104_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta_Valor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('meta', models.IntegerField()),
            ],
        ),
    ]
