# Generated by Django 2.1.15 on 2022-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_meta_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licencas_Faltando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('lincencas_faltando', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Placar_Licensas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('placar_licensas', models.IntegerField()),
            ],
        ),
    ]
