# Generated by Django 3.2.16 on 2022-11-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20221110_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PipelineC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('money', models.IntegerField()),
            ],
        ),
    ]
