# Generated by Django 3.2.16 on 2022-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_pipelinea_pipelineb_pipelinec'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pipelinea',
            old_name='nome',
            new_name='nome_a',
        ),
        migrations.RenameField(
            model_name='pipelinea',
            old_name='uf',
            new_name='uf_a',
        ),
        migrations.RenameField(
            model_name='pipelineb',
            old_name='money',
            new_name='money_b',
        ),
        migrations.RenameField(
            model_name='pipelineb',
            old_name='nome',
            new_name='nome_b',
        ),
        migrations.RenameField(
            model_name='pipelineb',
            old_name='uf',
            new_name='uf_b',
        ),
        migrations.RenameField(
            model_name='pipelinec',
            old_name='money',
            new_name='money_c',
        ),
        migrations.RenameField(
            model_name='pipelinec',
            old_name='nome',
            new_name='nome_c',
        ),
        migrations.RenameField(
            model_name='pipelinec',
            old_name='uf',
            new_name='uf_c',
        ),
        migrations.RemoveField(
            model_name='pipelinea',
            name='money',
        ),
        migrations.AddField(
            model_name='pipelinea',
            name='money_a',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
